// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.service3;

public interface authenticateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authenticate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstString = 10;</code>
   */
  java.lang.String getFirstString();
  /**
   * <code>string firstString = 10;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
