// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.service3;

public interface authenticateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authenticateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string loginDetails = 10;</code>
   */
  java.lang.String getLoginDetails();
  /**
   * <code>string loginDetails = 10;</code>
   */
  com.google.protobuf.ByteString
      getLoginDetailsBytes();
}
