// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package com.service3;

public interface authenticateReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authenticateReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 10;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 10;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
