// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.service1;

public interface containsStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *grpc has to convert these messages into bytes- that is what 1,2 and 3 are. That is what the 1 is here.
   * </pre>
   *
   * <code>string firstString = 10;</code>
   */
  java.lang.String getFirstString();
  /**
   * <pre>
   *grpc has to convert these messages into bytes- that is what 1,2 and 3 are. That is what the 1 is here.
   * </pre>
   *
   * <code>string firstString = 10;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
