// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package com.service1;

public interface containsStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:containsString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstString = 10;</code>
   */
  java.lang.String getFirstString();
  /**
   * <code>string firstString = 10;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
