// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package com.service2;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 10;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 10;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>int32 true = 1;</code>
   */
  int getTrue();

  /**
   * <code>int32 false = 2;</code>
   */
  int getFalse();
}
